---
abstract: 'consume Ant build files'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Ant-BuildFile
requires:
  Carp: 0
  English: 0
  Modern::Perl: 0
  Module::Pluggable: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Has::Sugar: 0
  MooseX::Has::Sugar::Minimal: 0
  MooseX::Singleton: 0.26
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  Path::Class: 0
  Readonly: 0
  Regexp::DefaultFlags: 0
  TryCatch: 0
  XML::Rabbit: 0.0.4
  XML::Rabbit::Node: 0.0.4
  XML::Rabbit::RootNode: 0
  namespace::autoclean: 0
  perl: 5.012
  utf8: 0
resources:
  bugtracker: http://github.com/mjgardner/XML-Ant-BuildFile/issues
version: 0.211
